services:
  smart-meter-api:
    build: .
    container_name: belgian-smart-meter-api
    privileged: false
    restart: unless-stopped
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - P1_PORT=/dev/ttyUSB0
      - P1_BAUDRATE=115200
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9039:9039"