name: Release Version

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to create releases
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          
      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Build binaries
        run: |
          # Create dist directory
          mkdir -p dist

          build_for_target() {
            local target=$1
            echo "Building ${target}"
            GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o dist/${target}-linux-amd64 cmd/${target}/main.go
            GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o dist/${target}-linux-arm64 cmd/${target}/main.go
            GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="-s -w" -o dist/${target}-linux-arm6 cmd/${target}/main.go
            GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-s -w" -o dist/${target}-linux-arm7 cmd/${target}/main.go
          }
                
          build_for_target interpreter_api
          build_for_target meter_collector
          
      - name: Create checksums
        run: |
          cd dist
          sha256sum * > checksums.txt
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION }}
          name: Release ${{ steps.version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/interpreter_api-*
            dist/meter_collector-*
            dist/checksums.txt
          body: |
            ## What's Changed
            
            Release ${{ steps.version.outputs.VERSION }} of interpreter_api
            
            ### Download the appropriate binary for your system:
            - **Linux x64**: `interpreter_api-linux-amd64`
            - **Linux ARM64**: `interpreter_api-linux-arm64` (Pi 4, Pi 5, newer 64-bit boards)
            - **Linux ARMv6**: `interpreter_api-linux-arm6` (Pi Zero, Pi 1, older boards)
            - **Linux ARMv7**: `interpreter_api-linux-arm7` (Pi 2, Pi 3, most common 32-bit ARM)
            
            Verify downloads with `checksums.txt`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}